In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = 999
dat_orig = pd.read_excel("2018_sales.xlsx", header = 1)
dat_orig.fillna(method='ffill', inplace=True)
dat_orig = dat_orig.filter(regex=r'(Wk.|Unnamed: 0|Unnamed: 1|Unnamed: 2)')
dat_orig.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Feb Wk. 1 2019,Feb Wk. 2 2019,Feb Wk. 3 2019,Feb Wk. 4 2019,Mar Wk. 5 2019,Mar Wk. 6 2019,Mar Wk. 7 2019,Mar Wk. 8 2019,Mar Wk. 9 2019,Apr Wk. 10 2019,Apr Wk. 11 2019,Apr Wk. 12 2019,Apr Wk. 13 2019,May Wk. 14 2019,May Wk. 15 2019,May Wk. 16 2019,May Wk. 17 2019,Jun Wk. 18 2019,Jun Wk. 19 2019,Jun Wk. 20 2019,Jun Wk. 21 2019,Jun Wk. 22 2019,Jul Wk. 23 2019,Jul Wk. 24 2019,Jul Wk. 25 2019,Jul Wk. 26 2019,Aug Wk. 27 2019,Aug Wk. 28 2019,Aug Wk. 29 2019,Aug Wk. 30 2019,Sep Wk. 31 2019,Sep Wk. 32 2019,Sep Wk. 33 2019,Sep Wk. 34 2019,Sep Wk. 35 2019,Oct Wk. 36 2019,Oct Wk. 37 2019,Oct Wk. 38 2019,Oct Wk. 39 2019,Nov Wk. 40 2019,Nov Wk. 41 2019,Nov Wk. 42 2019,Nov Wk. 43 2019,Dec Wk. 44 2019,Dec Wk. 45 2019,Dec Wk. 46 2019,Dec Wk. 47 2019,Dec Wk. 48 2019,Jan Wk. 49 2019,Jan Wk. 50 2019,Jan Wk. 51 2019,Jan Wk. 52 2019
0,Direct,Sls Total FP Rtl,LY,2.6191e+06,3.11482e+06,1.26302e+06,3.10634e+06,4.94786e+06,4.48451e+06,1.99622e+06,6.10595e+06,4.65447e+06,3.4179e+06,2.12765e+06,6.02738e+06,4.56318e+06,6.46613e+06,3.41393e+06,2.93784e+06,4.20344e+06,2.78572e+06,4.24735e+06,2.99027e+06,1.95681e+06,1.80254e+06,2.36174e+06,2.48979e+06,1.69979e+06,1.60573e+06,2.29515e+06,2.19364e+06,1.81738e+06,3.37993e+06,3.81247e+06,4.72602e+06,5.48783e+06,2.97255e+06,5.34449e+06,4.57149e+06,3.99308e+06,4.0983e+06,5.41473e+06,5.39372e+06,4.27014e+06,7.18727e+06,1.04607e+07,5.25634e+06,4.21524e+06,2.35427e+06,1.51287e+06,1.65111e+06,3.40117e+06,1.73363e+06,773961,2.12887e+06
1,Direct,Sls Total MD Rtl,LY,418697,1.28096e+06,2.86295e+06,1.49025e+06,1.09141e+06,1.85633e+06,2.34381e+06,1.21474e+06,1.76859e+06,613653,1.55391e+06,1.23227e+06,1.86073e+06,1.30668e+06,1.14679e+06,2.1711e+06,1.99288e+06,1.30856e+06,809572,727637,3.25918e+06,3.70596e+06,1.80211e+06,2.54092e+06,2.81471e+06,1.28752e+06,1.1542e+06,1.60537e+06,1.29413e+06,2.24379e+06,1.83228e+06,630941,424986,635694,820040,775590,1.00772e+06,1.01295e+06,902646,939332,1.66965e+06,1.00221e+06,1.57471e+06,964273,743994,965570,2.14527e+06,2.19711e+06,1.87944e+06,1.42259e+06,2.46773e+06,591970
2,Direct,Sls Total Rtl,LY,3.03779e+06,4.39577e+06,4.12597e+06,4.59658e+06,6.03927e+06,6.34084e+06,4.34003e+06,7.32069e+06,6.42306e+06,4.03155e+06,3.68156e+06,7.25965e+06,6.42391e+06,7.77282e+06,4.56072e+06,5.10894e+06,6.19632e+06,4.09429e+06,5.05692e+06,3.7179e+06,5.21599e+06,5.5085e+06,4.16385e+06,5.03072e+06,4.51451e+06,2.89325e+06,3.44934e+06,3.79901e+06,3.11151e+06,5.62372e+06,5.64475e+06,5.35696e+06,5.91282e+06,3.60824e+06,6.16453e+06,5.34708e+06,5.0008e+06,5.11125e+06,6.31738e+06,6.33306e+06,5.93978e+06,8.18947e+06,1.20354e+07,6.22062e+06,4.95924e+06,3.31984e+06,3.65814e+06,3.84822e+06,5.28061e+06,3.15622e+06,3.24169e+06,2.72084e+06
3,Direct,Sls Total FP U,LY,45660,59187,18413,50013,96095,88177,35225,114460,88038,64415,37244,103743,76577,131041,69266,46402,69532,48981,90057,65149,35758,28060,46854,51156,38565,22058,43713,38540,38177,59254,58620,81046,101669,50305,90661,78539,64949,62570,79031,88187,70103,138995,232955,111309,92066,48745,21558,24758,66300,31738,11443,32693
4,Direct,Sls Total MD U,LY,6235,42613,116496,51186,31134,72162,97720,45198,79963,19158,46561,37299,72394,43733,37296,78712,78946,41226,24728,20221,125874,149246,74762,105916,131318,64071,43903,73411,60906,92483,90384,13947,13202,14457,23533,25386,31463,24829,27926,33080,55953,34526,63617,35631,27840,34742,78473,92472,81460,68134,115223,19307

In [5]:
def format_sales(df):
    
    ids = list(df.iloc[:, np.r_[0:2]].columns)
    vals = list(df.iloc[:,3:].columns)
    
    melt = pd.melt(df, id_vars = ids, value_vars = vals, var_name = 'FISCAL_WK', value_name = 'SALES')
    
    melt.rename(columns={'Unnamed: 0':'Channel',
                      'Unnamed: 1': 'summation_type'
                          
                          }, 
                 inplace=True)
    
    sub = melt[melt['summation_type'] == "Sls Total Rtl"]
    sub[['Channel', 'SALES']].groupby('Channel').agg('sum')
    
    sub.FISCAL_WK = sub.FISCAL_WK.str[8:].copy()
    sub.FISCAL_WK = sub.FISCAL_WK.str[:2].copy()
    sub.FISCAL_WK = sub.FISCAL_WK.str.strip().copy()
    
    h1 = [1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6]
    h2 = [x+1 for x in h1]

    months = h1 + h2
    weeks = list(range(1, 53))

    month_map = pd.DataFrame()
    month_map['FISCAL_MO'] = months
    month_map['FISCAL_WK'] = weeks
    
    sub.FISCAL_WK = sub.FISCAL_WK.astype(str).astype(int)
    sales_fcst = pd.merge(sub, month_map, on='FISCAL_WK', how='inner')
    
    return sales_fcst

In [6]:
fcst = format_sales(dat_orig)
fcst.head()

  Channel summation_type  FISCAL_WK        SALES  FISCAL_MO
0  Direct  Sls Total Rtl          1  3.03779e+06          1
1  Retail  Sls Total Rtl          1  5.16914e+06          1
2  Direct  Sls Total Rtl          2  4.39577e+06          1
3  Retail  Sls Total Rtl          2  5.44481e+06          1
4  Direct  Sls Total Rtl          3  4.12597e+06          1